name: Debug All Methods
on: [push, workflow_dispatch]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium webdriver-manager undetected_chromedriver
    - name: Run debug script
      run: python debug_all_methods.py
    - name: Upload debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debug-files
        path: |
          debug_all_methods.log
          debug_response_*.html
